image: nplyusnin/stackoverclone-staging

servers:
  - 109.172.83.54

labels:
  traefik.http.routers.stackoverclone.entrypoints: websecure
  traefik.http.routers.stackoverclone.rule: Host(`stackoverclone-staging.plyusnin.dev`)
  traefik.http.routers.stackoverclone.tls.certresolver: letsencrypt

registry:
  username: nplyusnin
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DATABASE_URL: postgresql://postgres:postgres@109.172.83.54/stackoverclone_staging
  secret:
    - RAILS_MASTER_KEY

builder:
  args:
    RUBY_VERSION: 3.3.0

accessories:
  db:
    image: postgres:16.1-alpine
    host: 109.172.83.54
    port: 5432
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /data/postgres
    directories:
      - data:/data/postgres
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data

# Run on server
# mkdir -p /letsencrypt &&
#  touch /letsencrypt/acme.json &&
#  chmod 600 /letsencrypt/acme.json
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "me@plyusnin.dev"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
