service: stackoverclone

registry:
  username: nplyusnin
  password:
    - KAMAL_REGISTRY_PASSWORD

labels:
  traefik.http.routers.stackoverclone.entrypoints: websecure
  traefik.http.routers.stackoverclone.tls.certresolver: letsencrypt

accessories:
  db:
    image: postgres:16.1-alpine
    port: 5432
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /data/postgres
    directories:
      - data:/data/postgres

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "me@plyusnin.dev"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
