image: nplyusnin/stackoverclone-staging

servers:
  - 109.172.83.54

labels:
  traefik.http.routers.stackoverclone.rule: Host(`stackoverclone-staging.plyusnin.dev`)

env:
  clear:
    DATABASE_URL: postgresql://postgres:postgres@109.172.83.54/stackoverclone_staging
  secret:
    - RAILS_MASTER_KEY

builder:
  args:
    RUBY_VERSION: 3.3.0

accessories:
  db:
    host: 109.172.83.54
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data

# Run on server
# mkdir -p /letsencrypt && touch /letsencrypt/acme.json && chmod 600 /letsencrypt/acme.json
